name: 'Deploy Load Balancer - health probe'
run-name: 'Load Balancer - ${{inputs.environment}} purpose: ${{inputs.purpose}} : ${{inputs.requesttype}}'
on:
  workflow_dispatch:
    inputs:
      requesttype:
        type: choice
        required: true
        description: Request Type
        options:
            - Create Health Probe
            - Remove
        default: "Create Health Probe"
      environment:
        type: choice
        required: true
        description: Environment
        options:
          - DEV
          - UAT
          - QA
          - PROD
      location:
        type: choice
        required: true
        description: Deployment Location
        options:
          - Select the location
          - eastus2
          - uksouth
          - centralus
          - ukwest
      purpose:
        type: string
        required: true
        description: Purpose of the Load Balancer
      purposeRG:
        type: string
        required: true
        description: Resource Group Purpose.......... Hyphen designate an existing RG
      probes_protocols: 
        type: string
        required: true
        description: comma separated list of protocols for the probes
      probes_ports:
        type: string
        required: true
        description: comma separated list of ports for the probes
      probes_intervals_in_seconds:
        type: string
        required: true
        description: comma separated list of intervals in seconds for the probes
      probes_number_of_probes:
        type: string
        required: true
        description: comma separated list of number of probes for the probes
jobs:
  load_balancer_health_probe_create:
    if: (github.event.inputs.requesttype == 'Create Health Probe')
    name: 'Load Balancer ${{inputs.purpose}}'
    uses: ./.github/workflows/LBHealthProbe.yml
    secrets: inherit
    with:
      requesttype:                 '${{inputs.requesttype}}'
      environment:                 '${{inputs.environment}}'
      location:                    '${{inputs.location}}'
      purpose:                     '${{inputs.purpose}}'
      purposeRG:                   '${{inputs.purposeRG}}'
      probes_protocols:            '${{inputs.probes_protocols}}' 
      probes_ports:                '${{inputs.probes_ports}}'
      probes_intervals_in_seconds: '${{inputs.probes_intervals_in_seconds}}'
      probes_number_of_probes:     '${{inputs.probes_number_of_probes}}'

  load_balancer_health_probe_remove:
    if: (github.event.inputs.requesttype == 'Remove')
    name: 'Load Balancer ${{inputs.purpose}}'
    uses: ./.github/workflows/LBHealthProbe.yml
    secrets: inherit
    with:
      requesttype:                 '${{inputs.requesttype}}'
      environment:                 '${{inputs.environment}}'
      location:                    '${{inputs.location}}'
      purpose:                     '${{inputs.purpose}}'
      purposeRG:                   '${{inputs.purposeRG}}'
      probes_protocols:            '${{inputs.probes_protocols}}' 
      probes_ports:                '${{inputs.probes_ports}}'
      probes_intervals_in_seconds: '${{inputs.probes_intervals_in_seconds}}'
      probes_number_of_probes:     '${{inputs.probes_number_of_probes}}'