name: 'Health Porbe Load Balancer (Call)'
run-name: '${{github.actor}} - Adding/Updating/Removing LB health probes'
on:
  workflow_call:
    inputs:
      requestType:
        type: string
        required: false
      location:
        type: string
        required: true
      environment:
        type: string
        required: true
      purpose:
        type: string
        required: false
      purposeRG:
        type: string
        required: false
      probes_protocols:
        type: string
        required: true
      probes_ports:
        type: string
        required: true
      probes_intervals_in_seconds:
        type: string
        required: true
      probes_number_of_probes:
        type: string
        required: true

permissions:
  contents: read

jobs:
  lb-create:
    name: 'Create Azure Load Balancer'
    env:
      ARM_CLIENT_ID:        ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET:    ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_TENANT_ID:        ${{secrets.AZURE_TENANT_ID}}
      ARM_SUBSCRIPTION_ID:  ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ROOT_PATH:            'Azure/Azure-LB/LB-Rules'
    runs-on: 
      group: aks-runners # self-hosted runners
    environment: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
        working-directory: 'Azure/Azure-LB/LB-Rules'
    steps:
      - name: 'Checkout - Load Balancer'
        uses: actions/checkout@v3
      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify the required Node.js version  
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest      
      - id: envvars
        name: Set environment variables based on deployment environment
        run: |
          echo "BACKEND_STORAGE_ACCOUNT=${{ secrets.BACKEND_STORAGE_ACCOUNT }}" >> "$GITHUB_ENV"
          echo "BACKEND_RESOURCE_GROUP=${{ secrets.BACKEND_RESOURCE_GROUP }}" >> "$GITHUB_ENV"

      - name: 'Terraform Initialize - Load Balancer'
        run: terraform init -backend-config="resource_group_name=$BACKEND_RESOURCE_GROUP" -backend-config="storage_account_name=$BACKEND_STORAGE_ACCOUNT" -backend-config="container_name=terraform-state" -backend-config="key=${{ inputs.environment }}-${{ inputs.purpose }}-terraform.tfstate" -input=false
        env:
          TF_VAR_location:                     '${{inputs.location}}'
          TF_VAR_environment:                  '${{inputs.environment}}'
          TF_VAR_purpose:                      '${{inputs.purpose}}'
          TF_VAR_purpose_rg:                   '${{inputs.purposeRG}}'
          TF_VAR_probes_protocols:             '${{inputs.probes_protocols}}'
          TF_VAR_probes_ports:                 '${{inputs.probes_ports}}'
          TF_VAR_probes_intervals_in_seconds:  '${{inputs.probes_intervals_in_seconds}}'
          TF_VAR_probes_number_of_probes:      '${{inputs.probes_number_of_probes}}'

      - name: 'Terraform Plan - Load Balancer'
        if: ${{ inputs.requestType == 'Create Health Probe' }}
        run: terraform plan
        env:
          TF_VAR_location:                     '${{inputs.location}}'
          TF_VAR_environment:                  '${{inputs.environment}}'
          TF_VAR_purpose:                      '${{inputs.purpose}}'
          TF_VAR_purpose_rg:                   '${{inputs.purposeRG}}'
          TF_VAR_probes_protocols:             '${{inputs.probes_protocols}}'
          TF_VAR_probes_ports:                 '${{inputs.probes_ports}}'
          TF_VAR_probes_intervals_in_seconds:  '${{inputs.probes_intervals_in_seconds}}'
          TF_VAR_probes_number_of_probes:      '${{inputs.probes_number_of_probes}}'
      
      - name: 'Terraform Apply - Load Balancer'
        if: ${{ inputs.requestType == 'Create Health Probe' }}
        run: terraform apply -auto-approve
        env:
          TF_VAR_location:                     '${{inputs.location}}'
          TF_VAR_environment:                  '${{inputs.environment}}'
          TF_VAR_purpose:                      '${{inputs.purpose}}'
          TF_VAR_purpose_rg:                   '${{inputs.purposeRG}}'
          TF_VAR_probes_protocols:             '${{inputs.probes_protocols}}'
          TF_VAR_probes_ports:                 '${{inputs.probes_ports}}'
          TF_VAR_probes_intervals_in_seconds:  '${{inputs.probes_intervals_in_seconds}}'
          TF_VAR_probes_number_of_probes:      '${{inputs.probes_number_of_probes}}'
      
      - name: 'Terraform Remove - Load Balancer'
        if: ${{ inputs.requestType == 'Remove' }}
        run: terraform destroy -target=azurerm_lb_probe.tcp_probe -auto-approve
        env:
          TF_VAR_location:                     '${{inputs.location}}'
          TF_VAR_environment:                  '${{inputs.environment}}'
          TF_VAR_purpose:                      '${{inputs.purpose}}'
          TF_VAR_purpose_rg:                   '${{inputs.purposeRG}}'
          TF_VAR_probes_protocols:             '${{inputs.probes_protocols}}'
          TF_VAR_probes_ports:                 '${{inputs.probes_ports}}'
          TF_VAR_probes_intervals_in_seconds:  '${{inputs.probes_intervals_in_seconds}}'
          TF_VAR_probes_number_of_probes:      '${{inputs.probes_number_of_probes}}'